let
    Source = Csv.Document(File.Contents("C:\Users\maosk\OneDrive - DFDS\Documents\Logistics EA\Archi\elements.csv"),[Delimiter=";", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", type text}, {"Type", type text}, {"Name", type text}, {"Documentation", type text}, {"Specialization", type any}})
in
    #"Changed Type"